### ISSUE TITLE
Way to change the destination?

### ISSUE THREAD

**Issue by hansmorb** [robertdebock/ansible-role-nextcloud#2]
The way I am doing it right now is through editing the _nextcloud_destination in the vars file in the role but this can't be it. Could there be another way?

**Comment by robertdebock** [comment]
That's a good idea, let me rewrite a part of the roles variables for that.

**Comment by hansmorb** [comment]
Thank you very much, I highly appreciate it! :)

**Comment by robertdebock** [comment]
Version 2.2.0 allows setting `nextcloud_destination`.

Thanks again!
